
const fs = require('fs');
const path = require('path');

const RAW_DATA = {
    "Animals": [
        { word: "Lion", associationWord: "King" },
        { word: "Elephant", associationWord: "Trunk" },
        { word: "Giraffe", associationWord: "Neck" },
        { word: "Penguin", associationWord: "Tuxedo" },
        { word: "Kangaroo", associationWord: "Pouch" },
        { word: "Panda", associationWord: "Bamboo" },
        { word: "Snake", associationWord: "Hiss" },
        { word: "Eagle", associationWord: "Bald" },
        { word: "Shark", associationWord: "Jaws" },
        { word: "Dolphin", associationWord: "Flipper" },
        { word: "Dog", associationWord: "Bark" },
        { word: "Cat", associationWord: "Meow" },
        { word: "Wolf", associationWord: "Moon" },
        { word: "Bear", associationWord: "Honey" },
        { word: "Zebra", associationWord: "Stripes" },
        { word: "Rabbit", associationWord: "Carrot" },
        { word: "Turtle", associationWord: "Shell" },
        { word: "Owl", associationWord: "Hoot" },
        { word: "Monkey", associationWord: "Banana" },
        { word: "Horse", associationWord: "Saddle" },
        { word: "Tiger", associationWord: "Stripes" },
        { word: "Cheetah", associationWord: "Fast" },
        { word: "Gorilla", associationWord: "Chest" },
        { word: "Fox", associationWord: "Sly" },
        { word: "Whale", associationWord: "Big" },
        { word: "Bat", associationWord: "Vampire" },
        { word: "Frog", associationWord: "Prince" },
        { word: "Pig", associationWord: "Mud" },
        { word: "Cow", associationWord: "Milk" },
        { word: "Sheep", associationWord: "Wool" }
    ],
    "Foods": [
        { word: "Pizza", associationWord: "Pepperoni" },
        { word: "Burger", associationWord: "Bun" },
        { word: "Sushi", associationWord: "Roll" },
        { word: "Pasta", associationWord: "Italy" },
        { word: "Chocolate", associationWord: "Bar" },
        { word: "Ice Cream", associationWord: "Cone" },
        { word: "Taco", associationWord: "Shell" },
        { word: "Salad", associationWord: "Green" },
        { word: "Steak", associationWord: "Rare" },
        { word: "Fries", associationWord: "Ketchup" },
        { word: "Popcorn", associationWord: "Movie" },
        { word: "Donut", associationWord: "Hole" },
        { word: "Pancake", associationWord: "Syrup" },
        { word: "Waffle", associationWord: "Iron" },
        { word: "Cookie", associationWord: "Chip" },
        { word: "Apple", associationWord: "Red" },
        { word: "Banana", associationWord: "Yellow" },
        { word: "Grape", associationWord: "Wine" },
        { word: "Cheese", associationWord: "Mouse" },
        { word: "Bread", associationWord: "Toast" },
        { word: "Rice", associationWord: "Grain" },
        { word: "Soup", associationWord: "Bowl" },
        { word: "Sandwich", associationWord: "Club" },
        { word: "Hot Dog", associationWord: "Mustard" },
        { word: "Cake", associationWord: "Birthday" },
        { word: "Pie", associationWord: "Crust" },
        { word: "Bacon", associationWord: "Breakfast" },
        { word: "Egg", associationWord: "Yolk" },
        { word: "Butter", associationWord: "Toast" },
        { word: "Milk", associationWord: "Cow" }
    ],
    "Brands": [
        { word: "Apple", associationWord: "iPhone" },
        { word: "Nike", associationWord: "Just Do It" },
        { word: "McDonald's", associationWord: "Lovin' It" },
        { word: "Coca-Cola", associationWord: "Soda" },
        { word: "Google", associationWord: "Search" },
        { word: "Amazon", associationWord: "Prime" },
        { word: "Tesla", associationWord: "Electric" },
        { word: "Disney", associationWord: "Magic" },
        { word: "Netflix", associationWord: "Chill" },
        { word: "Samsung", associationWord: "Android" },
        { word: "Starbucks", associationWord: "Coffee" },
        { word: "Adidas", associationWord: "Stripes" },
        { word: "Microsoft", associationWord: "Windows" },
        { word: "Sony", associationWord: "PlayStation" },
        { word: "Lego", associationWord: "Block" },
        { word: "IKEA", associationWord: "Sweden" },
        { word: "Toyota", associationWord: "Car" },
        { word: "Gucci", associationWord: "Luxury" },
        { word: "Rolex", associationWord: "Watch" },
        { word: "Pepsi", associationWord: "Blue" },
        { word: "Facebook", associationWord: "Blue" },
        { word: "Instagram", associationWord: "Photo" },
        { word: "Twitter", associationWord: "Bird" },
        { word: "YouTube", associationWord: "Video" },
        { word: "Uber", associationWord: "Taxi" },
        { word: "Airbnb", associationWord: "Stay" },
        { word: "Spotify", associationWord: "Music" },
        { word: "Ferrari", associationWord: "Red" },
        { word: "Lamborghini", associationWord: "Bull" },
        { word: "BMW", associationWord: "German" }
    ],
    "Objects": [
        { word: "Phone", associationWord: "Call" },
        { word: "Chair", associationWord: "Sit" },
        { word: "Table", associationWord: "Legs" },
        { word: "Car", associationWord: "Drive" },
        { word: "Book", associationWord: "Read" },
        { word: "Pen", associationWord: "Write" },
        { word: "Shoe", associationWord: "Foot" },
        { word: "Watch", associationWord: "Time" },
        { word: "Glasses", associationWord: "See" },
        { word: "Key", associationWord: "Lock" },
        { word: "Door", associationWord: "Knob" },
        { word: "Bed", associationWord: "Sleep" },
        { word: "Lamp", associationWord: "Light" },
        { word: "Scissors", associationWord: "Cut" },
        { word: "Knife", associationWord: "Sharp" },
        { word: "Cup", associationWord: "Drink" },
        { word: "Mirror", associationWord: "Reflect" },
        { word: "Umbrella", associationWord: "Rain" },
        { word: "Bag", associationWord: "Carry" },
        { word: "Hat", associationWord: "Head" },
        { word: "Computer", associationWord: "Type" },
        { word: "Mouse", associationWord: "Click" },
        { word: "Keyboard", associationWord: "QWERTY" },
        { word: "Bottle", associationWord: "Water" },
        { word: "Plate", associationWord: "Food" },
        { word: "Fork", associationWord: "Prongs" },
        { word: "Spoon", associationWord: "Soup" },
        { word: "Television", associationWord: "Screen" },
        { word: "Remote", associationWord: "Control" },
        { word: "Pillow", associationWord: "Soft" }
    ],
    "Anime": [
        { word: "Naruto", associationWord: "Ninja" },
        { word: "One Piece", associationWord: "Pirate" },
        { word: "Dragon Ball", associationWord: "Goku" },
        { word: "Attack on Titan", associationWord: "Wall" },
        { word: "Pokemon", associationWord: "Pikachu" },
        { word: "Demon Slayer", associationWord: "Sword" },
        { word: "Death Note", associationWord: "Apple" },
        { word: "Sailor Moon", associationWord: "Transformation" },
        { word: "My Hero Academia", associationWord: "Quirk" },
        { word: "Fullmetal Alchemist", associationWord: "Transmutation" },
        { word: "Spirited Away", associationWord: "Bathhouse" },
        { word: "Totoro", associationWord: "Forest" },
        { word: "Evangelion", associationWord: "Eva" },
        { word: "One Punch Man", associationWord: "Bald" },
        { word: "Bleach", associationWord: "Soul Reaper" },
        { word: "Hunter x Hunter", associationWord: "Hunter" },
        { word: "Jojo", associationWord: "Stand" },
        { word: "Cowboy Bebop", associationWord: "Space" },
        { word: "Akira", associationWord: "Bike" },
        { word: "Yu-Gi-Oh", associationWord: "Card" },
        { word: "Ghibli", associationWord: "Studio" },
        { word: "Chainsaw Man", associationWord: "Devil" },
        { word: "Jujutsu Kaisen", associationWord: "Curse" },
        { word: "Spy x Family", associationWord: "Anya" },
        { word: "Haikyuu", associationWord: "Volleyball" },
        { word: "Tokyo Ghoul", associationWord: "Mask" },
        { word: "Code Geass", associationWord: "Eye" },
        { word: "Fairy Tail", associationWord: "Guild" },
        { word: "Sword Art Online", associationWord: "VR" },
        { word: "Gintama", associationWord: "Samurai" }
    ],
    "Video Games": [
        { word: "Minecraft", associationWord: "Block" },
        { word: "Fortnite", associationWord: "Build" },
        { word: "Mario", associationWord: "Jump" },
        { word: "Pokemon", associationWord: "Catch" },
        { word: "Call of Duty", associationWord: "War" },
        { word: "GTA", associationWord: "Car" },
        { word: "Zelda", associationWord: "Hyrule" },
        { word: "Sonic", associationWord: "Ring" },
        { word: "Tetris", associationWord: "Line" },
        { word: "Pac-Man", associationWord: "Ghost" },
        { word: "Among Us", associationWord: "Sus" },
        { word: "Roblox", associationWord: "Blox" },
        { word: "League of Legends", associationWord: "Rift" },
        { word: "Overwatch", associationWord: "Hero" },
        { word: "FIFA", associationWord: "Goal" },
        { word: "Sims", associationWord: "Life" },
        { word: "Final Fantasy", associationWord: "Crystal" },
        { word: "Halo", associationWord: "Spartan" },
        { word: "Witcher", associationWord: "Monster" },
        { word: "Skyrim", associationWord: "Dragon" },
        { word: "Elden Ring", associationWord: "Ring" },
        { word: "Dark Souls", associationWord: "Bonfire" },
        { word: "God of War", associationWord: "Boy" },
        { word: "Spider-Man", associationWord: "Web" },
        { word: "Last of Us", associationWord: "Zombie" },
        { word: "Red Dead Redemption", associationWord: "Cowboy" },
        { word: "Cyberpunk", associationWord: "City" },
        { word: "Valorant", associationWord: "Spike" },
        { word: "Apex Legends", associationWord: "Squad" },
        { word: "Destiny", associationWord: "Light" }
    ],
    "TV Shows": [
        { word: "Friends", associationWord: "Cafe" },
        { word: "Game of Thrones", associationWord: "Throne" },
        { word: "Stranger Things", associationWord: "Eleven" },
        { word: "Breaking Bad", associationWord: "Cook" },
        { word: "The Office", associationWord: "Boss" },
        { word: "Squid Game", associationWord: "Doll" },
        { word: "The Simpsons", associationWord: "Yellow" },
        { word: "Spongebob", associationWord: "Square" },
        { word: "Rick and Morty", associationWord: "Science" },
        { word: "Walking Dead", associationWord: "Walker" },
        { word: "Mandalorian", associationWord: "Helmet" },
        { word: "The Boys", associationWord: "Hero" },
        { word: "Sherlock", associationWord: "Detective" },
        { word: "Black Mirror", associationWord: "Future" },
        { word: "The Crown", associationWord: "Royal" },
        { word: "Money Heist", associationWord: "Bank" },
        { word: "The Witcher", associationWord: "Sword" },
        { word: "House of the Dragon", associationWord: "Targaryen" },
        { word: "Better Call Saul", associationWord: "Lawyer" },
        { word: "Family Guy", associationWord: "Dog" },
        { word: "South Park", associationWord: "Colorado" },
        { word: "Futurama", associationWord: "Delivery" },
        { word: "Seinfeld", associationWord: "Nothing" },
        { word: "Brooklyn 99", associationWord: "Police" },
        { word: "Parks and Rec", associationWord: "Government" },
        { word: "Ted Lasso", associationWord: "Coach" },
        { word: "Succession", associationWord: "CEO" },
        { word: "Euphoria", associationWord: "Teen" },
        { word: "Wednesday", associationWord: "Addams" },
        { word: "Last of Us", associationWord: "Cordyceps" }
    ],
    "Celebrities": [
        { word: "Taylor Swift", associationWord: "Song" },
        { word: "Elon Musk", associationWord: "Mars" },
        { word: "Michael Jackson", associationWord: "Dance" },
        { word: "Beyonce", associationWord: "Single" },
        { word: "Messi", associationWord: "Goal" },
        { word: "Ronaldo", associationWord: "Seven" },
        { word: "Donald Trump", associationWord: "Tower" },
        { word: "Dwayne Johnson", associationWord: "Rock" },
        { word: "Tom Cruise", associationWord: "Mission" },
        { word: "Brad Pitt", associationWord: "Hollywood" },
        { word: "Marilyn Monroe", associationWord: "Blonde" },
        { word: "Albert Einstein", associationWord: "Physics" },
        { word: "Kim Kardashian", associationWord: "Famous" },
        { word: "Justin Bieber", associationWord: "Pop" },
        { word: "Will Smith", associationWord: "Prince" },
        { word: "Oprah", associationWord: "Show" },
        { word: "Ariana Grande", associationWord: "High Note" },
        { word: "Billie Eilish", associationWord: "Hair" },
        { word: "Drake", associationWord: "Rapper" },
        { word: "Eminem", associationWord: "Rap God" },
        { word: "Kanye West", associationWord: "Yeezy" },
        { word: "Rihanna", associationWord: "Umbrella" },
        { word: "Lady Gaga", associationWord: "Poker" },
        { word: "Kylie Jenner", associationWord: "Lips" },
        { word: "Selena Gomez", associationWord: "Wizard" },
        { word: "Harry Styles", associationWord: "Direction" },
        { word: "Zendaya", associationWord: "Dune" },
        { word: "Tom Holland", associationWord: "Spider" },
        { word: "Johnny Depp", associationWord: "Pirate" },
        { word: "Leonardo DiCaprio", associationWord: "Oscar" }
    ],
    "Locations": [
        { word: "Paris", associationWord: "France" },
        { word: "New York", associationWord: "City" },
        { word: "London", associationWord: "Bridge" },
        { word: "Tokyo", associationWord: "Japan" },
        { word: "Egypt", associationWord: "Sand" },
        { word: "Australia", associationWord: "Island" },
        { word: "Brazil", associationWord: "Carnival" },
        { word: "China", associationWord: "Wall" },
        { word: "Italy", associationWord: "Boot" },
        { word: "India", associationWord: "Spice" },
        { word: "Dubai", associationWord: "Tall" },
        { word: "Hawaii", associationWord: "Volcano" },
        { word: "Hollywood", associationWord: "Film" },
        { word: "Las Vegas", associationWord: "Money" },
        { word: "Moon", associationWord: "Space" },
        { word: "Mars", associationWord: "Planet" },
        { word: "Antarctica", associationWord: "Cold" },
        { word: "Amazon Rainforest", associationWord: "Trees" },
        { word: "Sahara Desert", associationWord: "Hot" },
        { word: "Mount Everest", associationWord: "Peak" },
        { word: "Rome", associationWord: "Colosseum" },
        { word: "Greece", associationWord: "Myth" },
        { word: "Berlin", associationWord: "Wall" },
        { word: "Amsterdam", associationWord: "Canal" },
        { word: "Grand Canyon", associationWord: "Deep" },
        { word: "Niagara Falls", associationWord: "Water" },
        { word: "Great Barrier Reef", associationWord: "Coral" },
        { word: "Taj Mahal", associationWord: "White" },
        { word: "Machu Picchu", associationWord: "Inca" },
        { word: "Petra", associationWord: "Rock" }
    ],
    "Movies": [
        { word: "Titanic", associationWord: "Ship" },
        { word: "Avatar", associationWord: "Blue" },
        { word: "Star Wars", associationWord: "Space" },
        { word: "Harry Potter", associationWord: "Magic" },
        { word: "Avengers", associationWord: "Team" },
        { word: "Jurassic Park", associationWord: "Dinosaur" },
        { word: "The Matrix", associationWord: "Reality" },
        { word: "The Lion King", associationWord: "Pride" },
        { word: "Frozen", associationWord: "Snow" },
        { word: "Joker", associationWord: "Clown" },
        { word: "The Godfather", associationWord: "Mafia" },
        { word: "Inception", associationWord: "Dream" },
        { word: "Shrek", associationWord: "Ogre" },
        { word: "Toy Story", associationWord: "Toy" },
        { word: "Spider-Man", associationWord: "Hero" },
        { word: "Batman", associationWord: "Bat" },
        { word: "Superman", associationWord: "Krypton" },
        { word: "Barbie", associationWord: "Doll" },
        { word: "Oppenheimer", associationWord: "Bomb" },
        { word: "Lord of the Rings", associationWord: "Ring" },
        { word: "Hunger Games", associationWord: "Arrow" },
        { word: "Twilight", associationWord: "Vampire" },
        { word: "Pirates of the Caribbean", associationWord: "Sea" },
        { word: "Fast and Furious", associationWord: "Car" },
        { word: "Transformers", associationWord: "Robot" },
        { word: "Indiana Jones", associationWord: "Whip" },
        { word: "Black Panther", associationWord: "Wakanda" },
        { word: "Forrest Gump", associationWord: "Run" },
        { word: "Back to the Future", associationWord: "Time" },
        { word: "Coco", associationWord: "Music" }
    ]
};

const encoded = btoa(JSON.stringify(RAW_DATA));

const fileContent = `
// This file contains the protected game content.
// The data is Base64 encoded to prevent casual inspection.

// Helper to decode data
const decodeData = (encoded: string) => {
  try {
    return JSON.parse(atob(encoded));
  } catch (e) {
    console.error("Failed to decode game data", e);
    return {};
  }
};

// THE PROTECTED DATA BLOB
const PROTECTED_DATA_STRING = "${encoded}";

let cachedData: Record<string, Array<{ word: string, associationWord: string }>> | null = null;

export const getGameContent = (category: string): { word: string, associationWord: string } => {
  if (!cachedData) {
    cachedData = decodeData(PROTECTED_DATA_STRING);
  }

  const categoryData = cachedData?.[category] || [];
  
  if (categoryData.length === 0) {
    // Fallback if category empty or not found
    return { word: "Error", associationWord: "Error" };
  }

  const randomIndex = Math.floor(Math.random() * categoryData.length);
  return categoryData[randomIndex];
};
`;

const outputPath = path.resolve(__dirname, '../data/gameContent.ts');
fs.writeFileSync(outputPath, fileContent);

console.log(`Game content generated at ${outputPath}`);
